/**
 * ChurnGuard Display Module
 * Handles UI updates, streaming, and dashboard visualization.
 */

(function () {
    'use strict';

    window.generateChurnResponse = async function () {
        // Collect Data
        const input = document.getElementById('churn-ticket-input')?.value;
        if (!input) {
            showNotification('Please enter the customer ticket.', 'warning');
            return;
        }

        // Show Loading
        const loadingDiv = appendNotionMessage({
            role: 'assistant',
            content: `
            <div id="churn-loading" style="padding: 1.5rem; border: 1px solid #b91c1c; background: #fef2f2; border-radius: 8px;">
                <div style="display: flex; align-items: center; gap: 10px; color: #b91c1c; font-weight: 500; margin-bottom: 1rem;">
                    <div style="width: 20px; height: 20px; border: 2px solid #ef4444; border-top-color: transparent; border-radius: 50%; animation: spin 1s linear infinite;"></div>
                    <span>Analyzing Risk & Drafting Strategy...</span>
                </div>
                <div id="churn-stream-preview" style="font-family: 'Georgia', serif; font-size: 0.95rem; color: #374151; line-height: 1.6;"></div>
            </div>
            <style>@keyframes spin { to { transform: rotate(360deg); } }</style>`
        });

        // Set up Stream Callback
        let streamedText = '';
        window.onChurnStreamUpdate = function (text) {
            streamedText += text;
            const preview = document.getElementById('churn-stream-preview');
            if (preview) {
                preview.innerText = streamedText;
            }
        };

        try {
            const response = await window.generateChurnResponseWithAI();

            // Remove Loading
            const loader = document.getElementById('churn-loading');
            if (loader) loader.closest('.message').remove();

            // Store in History/State
            window.churnState.currentDraft = response;
            window.churnState.history.push({
                timestamp: new Date().toISOString(),
                risk: window.churnState.analysis?.risk_score,
                response: response
            });

            // Display Final
            displayChurnResult(response, window.churnState.analysis);

        } catch (error) {
            showNotification('Error generating response: ' + error.message, 'error');
            const loader = document.getElementById('churn-loading');
            if (loader) loader.innerHTML = `<span style="color:red">Error: ${error.message}</span>`;
        } finally {
            window.onChurnStreamUpdate = null;
        }
    };

    function displayChurnResult(text, analysis) {
        // Determine Risk Color
        const risk = analysis?.risk_score || 0;
        let riskColor = '#22c55e'; // Green
        let riskLabel = 'Low Risk';
        if (risk > 40) { riskColor = '#eab308'; riskLabel = 'Medium Risk'; }
        if (risk > 75) { riskColor = '#ef4444'; riskLabel = 'CRITICAL RISK'; }

        const content = `
<div class="churn-result" style="font-family: 'Inter', sans-serif; border: 2px solid ${riskColor}; border-radius: 12px; overflow: hidden; margin: 1rem 0;">
    <!-- Header / HUD -->
    <div style="background: linear-gradient(135deg, #1f2937 0%, #111827 100%); color: white; padding: 1rem 1.5rem;">
        <div style="display: flex; justify-content: space-between; align-items: start;">
            <div>
                <h3 style="margin: 0; font-size: 1.1rem; font-weight: 700; color: white;">Retention Strategy</h3>
                <p style="margin: 4px 0 0; font-size: 0.85rem; opacity: 0.8;">Generated by ChurnGuard</p>
            </div>
            <div style="text-align: right;">
                <div style="background: ${riskColor}; padding: 4px 10px; border-radius: 12px; font-weight: 800; font-size: 0.8rem; display: inline-block;">
                    ${riskLabel} (${risk}%)
                </div>
            </div>
        </div>
        
        <!-- Analysis Grid -->
        <div style="margin-top: 1rem; display: grid; grid-template-columns: 1fr 1fr; gap: 10px; font-size: 0.85rem; background: rgba(255,255,255,0.1); padding: 10px; border-radius: 8px;">
            <div><strong>Root Cause:</strong> ${analysis?.root_cause || 'N/A'}</div>
            <div><strong>Sentiment:</strong> ${analysis?.sentiment || 'N/A'}</div>
            <div style="grid-column: span 2; color: #fca5a5;"><strong>Recommended Action:</strong> ${analysis?.action || 'Review'}</div>
        </div>
    </div>

    <!-- Content -->
    <div style="background: #ffffff; padding: 2rem; max-height: 500px; overflow-y: auto; font-family: 'Georgia', serif; line-height: 1.6; color: #1a1a1a;">
        <div style="white-space: pre-wrap; word-wrap: break-word;">${escapeHtml(text)}</div>
    </div>

    <!-- Actions -->
    <div style="background: #f8fafc; padding: 1rem 1.5rem; border-top: 1px solid #e2e8f0; display: flex; gap: 0.75rem; flex-wrap: wrap;">
        <button onclick="window.copyChurnToClipboard()" style="flex: 1; padding: 0.75rem; background: #1f2937; color: white; border: none; border-radius: 6px; font-weight: 500; cursor: pointer;">
            📋 Copy
        </button>
        <button onclick="window.insertChurnToDoc()" style="flex: 1; padding: 0.75rem; background: #6366f1; color: white; border: none; border-radius: 6px; font-weight: 500; cursor: pointer;">
            📄 Write to CRM/Doc
        </button>
        ${risk > 75 ? `
        <button onclick="alert('Sent priority alert to CSM Manager via Slack.')" style="flex: 1; padding: 0.75rem; background: #dc2626; color: white; border: none; border-radius: 6px; font-weight: 500; cursor: pointer; display: flex; align-items: center; justify-content: center; gap: 6px;">
            🚨 Escalate
        </button>` : ''}
    </div>
</div>`;

        appendNotionMessage({ role: 'assistant', content: content });
        scrollToNotionBottom();
    }

    // --- Utilities ---

    window.copyChurnToClipboard = function () {
        if (!window.churnState.currentDraft) return;
        navigator.clipboard.writeText(window.churnState.currentDraft)
            .then(() => showNotification('Copied', 'success'));
    };

    window.insertChurnToDoc = async function () {
        if (!window.churnState.currentDraft) return;
        if (window.editorjs) {
            try {
                await window.editorjs.blocks.insert('paragraph', {
                    text: window.churnState.currentDraft
                });
                showNotification('Inserted', 'success');
            } catch (e) {
                console.error(e);
            }
        }
    };

    function escapeHtml(text) {
        const div = document.createElement('div');
        div.textContent = text;
        return div.innerHTML;
    }

    console.log('✅ ChurnGuard Display loaded');
})();
