/**
 * InsuranceGuard Display Module
 * Renders the generated letters with appropriate styling for B2B vs B2C.
 */

(function () {
    'use strict';

    window.displayInsuranceResult = function (text, mode) {
        const isInsurer = mode === 'insurer';

        const color = isInsurer ? '#1e40af' : '#047857';
        const title = isInsurer ? 'NOTICE OF ADVERSE DETERMINATION' : 'FORMAL APPEAL OF DENIAL';
        const badge = isInsurer ? 'REGULATORY COMPLIANT' : 'ADVOCATE REVIEWED';

        const content = `
<div class="insurance-result" style="font-family: 'Times New Roman', serif; border: 1px solid #e5e7eb; border-radius: 2px; margin: 1rem 0; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1); background: white;">
    <!-- Header -->
    <div style="background: ${isInsurer ? '#f1f5f9' : '#ecfdf5'}; padding: 1rem 1.5rem; border-bottom: 1px solid #e5e7eb; display: flex; justify-content: space-between; align-items: center;">
        <div>
            <h3 style="margin: 0; font-size: 1.1rem; font-weight: 700; color: ${color};">${title}</h3>
            <p style="margin: 4px 0 0; font-size: 0.8rem; color: #6b7280;">Generated by InsuranceGuard AI</p>
        </div>
        <span style="background: white; color: ${color}; padding: 4px 8px; border-radius: 4px; font-size: 0.7rem; font-weight: 600; border: 1px solid ${color};">
            ${badge}
        </span>
    </div>

    <!-- Content -->
    <div style="padding: 2rem; max-height: 500px; overflow-y: auto; line-height: 1.6; color: #111827; font-size: 1rem;">
        <div style="white-space: pre-wrap; word-wrap: break-word;">${escapeHtml(text)}</div>
    </div>

    <!-- Actions -->
    <div style="background: #f9fafb; padding: 1rem 1.5rem; border-top: 1px solid #e5e7eb; display: flex; gap: 0.75rem;">
        <button onclick="navigator.clipboard.writeText(this.closest('.insurance-result').querySelector('div[style*=\\'white-space\\']').innerText)" style="flex: 1; padding: 0.75rem; background: white; color: #374151; border: 1px solid #d1d5db; border-radius: 4px; font-weight: 600; cursor: pointer; transition: all 0.2s; font-family: 'Segoe UI', sans-serif;">
            Copy Text
        </button>
        <button onclick="window.insertInsuranceToDoc(this)" style="flex: 1; padding: 0.75rem; background: ${color}; color: white; border: none; border-radius: 4px; font-weight: 600; cursor: pointer; transition: all 0.2s; font-family: 'Segoe UI', sans-serif;">
            Save to Document
        </button>
    </div>
</div>`;

        appendNotionMessage({ role: 'assistant', content: content });
        scrollToNotionBottom();
    };

    window.insertInsuranceToDoc = async function (btn) {
        const text = btn.closest('.insurance-result').querySelector('div[style*="white-space"]').innerText;
        if (window.editorjs && text) {
            try {
                // Header
                await window.editorjs.blocks.insert('header', {
                    text: window.insuranceState.mode === 'insurer' ? 'DENIAL LETTER' : 'APPEAL LETTER',
                    level: 2
                });
                // Content
                const paragraphs = text.split(/\n\n+/);
                for (const p of paragraphs) {
                    await window.editorjs.blocks.insert('paragraph', { text: p });
                }
                showNotification('Filed to Record', 'success');
            } catch (e) {
                console.error(e);
            }
        }
    };

    function escapeHtml(text) {
        const div = document.createElement('div');
        div.textContent = text;
        return div.innerHTML;
    }

    console.log('✅ InsuranceGuard Display loaded');
})();
